spring:
  data:
    mongodb:
      uri: ${AUTHENTICATOR_DB_URI}

email-sender-client:
  url: http://${EMAIL_SENDER_SERVICE_SERVICE_HOST}:8080
  read-timeout: 10000ms
  connect-timeout: 1000ms

token:
  expiration: P90D # 3 months
  secret-key: ${TOKEN_SECRET_KEY}
